epochs: 15
model_name: "Dr-BERT/DrBERT-7GB"
batch_size: 16
max_position_embeddings: 512
weight_decay: 0.01
learning_rate: 1e-4
output_dir: "../save_models/"
data_dir: "../data/"
subset: "emea"
fewshot: 1.0