epochs: 25
model_name: Dr-BERT/DrBERT-7GB
batch_size: 16
weight_decay: 0.01
learning_rate: 2.0e-5
output_dir: "../save_models/"
run_dir: "../runs/"
data_dir: "../data/"
subset: 'task_2'
fewshot: 1.0
task: "deft2020-cls"
dataset: "DrBenchmark/DEFT2020"