epochs: 35
model_name: Dr-BERT/DrBERT-7GB
# for an effective batch_size of 12
gradient_accumulation_steps: 12
batch_size: 1
weight_decay: 0.01
learning_rate: 2.0e-5
output_dir: "../save_models/"
run_dir: "../runs/"
data_dir: "../data/"
subset: "source"
fewshot: 1.0
task: "morfitt-cls"
dataset: "DrBenchmark/MORFITT"